NUM_WORKER_NODES=3

Vagrant.configure("2") do |config|
  # Use Ubuntu Server
  config.vm.box = "bento/ubuntu-24.04"

  # Configure master node
  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.56.10"
    master.vm.provider "virtualbox" do |v|
      v.name = "k8s-master"
      v.memory = 4096
      v.cpus = 2
    end
  end

  # Configure worker nodes
  (1..NUM_WORKER_NODES).each do |i|
    config.vm.define "worker-#{i}" do |worker|
      worker.vm.hostname = "worker-#{i}"
      worker.vm.network "private_network", ip: "192.168.56.1#{i}"
      worker.vm.provider "virtualbox" do |v|
        v.name = "k8s-worker-#{i}"
        v.memory = 2048
        v.cpus = 1
      end
    end
  end
end
